version: '3.3'

services: 
    lb:
        image: nginx:1.21.0
        container_name: lb
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - my-keycloak
            - my-api
        networks:
            - my-net
        ports:
            - 80:80

    my-api:
        image: maven
        volumes: 
            - "../keycloak-auth/:/app"
            - "~/.m2:/root/.m2"
        ports:
          - "8085:8085"
        working_dir: /app
        command: "mvn compile -Dquarkus.http.host=0.0.0.0 quarkus:dev"
        container_name: my-api
        networks:
            - my-net

    my-keycloak:
        image: jboss/keycloak:12.0.4
        container_name: my-keycloak
        volumes: 
            - ./realm-export.json:/home/realm-export.json
        environment:
            # KEYCLOAK_FRONTEND_URL: 'http://172.17.0.1:8080/auth'
            # KEYCLOAK_FRONTEND_URL: 'http://my-keycloak:8080/auth'
            PROXY_ADDRESS_FORWARDING: "true"
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_IMPORT: /home/realm-export.json
        command: [
            -b 0.0.0.0
            -Dkeycloak.profile.feature.upload_scripts=enabled
        ]
        ports:
            - "8080:8080"
        networks: 
            - my-net
    
    keycloak-angular:
        build:
            context: ../keycloak-angular/
            dockerfile: keycloak-angular.Dockerfile
        # ports:
        #     - "80:80"
        container_name: keycloak-angular
        depends_on:
            - my-keycloak
            - my-api
        volumes:
            - ../keycloak-angular:/opt/web
            - ../keycloak-angular/node_modules:/opt/web/node_modules
            - ../keycloak-angular/dist:/opt/web/dist
        networks:
            - my-net


# volumes:
#     fc-dashboard-portainer-data:
#     fc-dashboard-pgadmin-data:
#     fc-dashboard-pg-data:
#         driver: local
    
    
networks:
    my-net:
        driver: bridge