version: '3.3'

services: 
    lb:
        image: nginx:1.21.0
        container_name: lb
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
            - my-api
        networks:
            - my-net
        ports:
            - 80:80

    my-api:
        image: maven
        volumes: 
            - "../keycloak-proxy/:/app"
            - "~/.m2:/root/.m2"
        ports:
          - "8085:8085"
        working_dir: /app
        command: "mvn compile -Dquarkus.http.host=0.0.0.0 quarkus:dev"
        container_name: my-api
        networks:
            - my-net

    my-keycloak:
        image: jboss/keycloak:12.0.4
        container_name: my-keycloak
        volumes: 
            - ./realm-export.json:/home/realm-export.json
        environment:
            KEYCLOAK_FRONTEND_URL: 'http://localhost/auth/'
            PROXY_ADDRESS_FORWARDING: "true"
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_IMPORT: /home/realm-export.json
        command: [
            -Dkeycloak.profile.feature.upload_scripts=enabled
        ]
        networks: 
            - my-net


# volumes:
#     fc-dashboard-portainer-data:
#     fc-dashboard-pgadmin-data:
#     fc-dashboard-pg-data:
#         driver: local
    
    
networks:
    my-net:
        driver: bridge